name: Deploy Website to cPanel

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Get the latest code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Check PHP and Composer
      - name: Check PHP and Composer
        run: |
          php --version
          composer --version

      # 3. Install frontend dependencies
      - name: Install frontend dependencies
        run: npm ci

      # 4. Build frontend
      - name: Build frontend
        run: npm run build

      # 5. Install Laravel dependencies
      - name: Install PHP dependencies
        run: |
          composer install \
            --optimize-autoloader \
            --no-interaction

      # 6. Install Zip & FTP client
      - name: Install Zip and FTP client
        run: |
          sudo apt-get update
          sudo apt-get install -y zip lftp

      # 7. Compress project files into a single ZIP
      - name: Archive project files
        run: |
          zip -r deploy.zip . -x ".git/*" ".github/*" "node_modules/*"

      # 8. Deploy to cPanel
      - name: Deploy to cPanel
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "Checking FTP server..."
          lftp -c "
            set ftp:ssl-allow true;
            set ssl:verify-certificate false;
            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
            put deploy.zip;
            put unzip.php;
            quit;
          "
